language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install

# command to run tests
script:
  - pytest --cov

after_success:
  - codecov
