language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install lxml
  - pip install requests
  - pip install pystache
  - pip install python-magic
  - pip install tika
  - pip install opf-fido

# command to run tests
script: python corptest/scraper.py
