language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - sudo apt-get install python-lxml python-requests
# command to run tests
script: python corptest/scraper.py
