language: python
python:
  # Disable Python 2 build 10/05/2017- "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - sudo apt-get install -y python-dev libxml2-dev libxslt1-dev zlib1g-dev python3-dev
  - pip install pytest-cov codecov codacy-coverage
  - python setup.py install

# command to run tests
script:
  - pytest --cov=corptest ./tests/

after_success:
  - coverage xml
  - codecov
  - python-codacy-coverage -r coverage.xml
