language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
  - pip install codacy-coverage


  - python setup.py install

# command to run tests
script:
  - pytest --cov

after_success:
  - codecov
  - coverage xml -i
  - python-codacy-coverage -r coverage.xml

