language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
  - pip install codacy-coverage

# command to run tests
script:
  - pytest --cov=corptest

after_success:
  - coverage xml
  - codecov
  - python-codacy-coverage -r coverage.xml
